---
driver:
  name: docker
  use_sudo: false
  customize:
    memory: 1024

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec
  # sudo: false # if 'true' (default) inSpec will run tests as 'root', rather than 'kitchen'
  format: doc

platforms:
  - name: ubuntu-14.04
  # - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[Trimmomatic::default]
    attributes:
